### ISSUE TITLE
Unable to launch Default mobile browser

### ISSUE THREAD

**Issue by NibhaSanghai** [saikrishna321/VodQa_MobileAutomationWorkShop#2]
My appium node is up with following config:

> Starting Node Server
> warn: Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version. Please upgrade!
> info: Welcome to Appium v1.4.0 (REV 8f63e2f91ef7907aed8bda763f4e5ca08e86970a)
> info: Appium REST http interface listener started on 127.0.0.1:4747
> info: [debug] Non-default server args: {"address":"127.0.0.1","port":4747,"noReset":true,"logNoColors":true,"deviceName":"Samsung ","platformName":"Android","platformVersion":"18","automationName":"Selendroid","browserName":"Browser","optionalIntentArguments":"www.google.com"}

Java code(copied yours):
try {
        AppiumDriver driver;
        WebDriverWait wait;
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName", "10.4.21.140:5555");
        capabilities.setCapability("platformVersion", "5.0.1");
        capabilities.setCapability("browserName", "browser");
        capabilities.setCapability("setJavaScriptEnabled", true);

```
        driver = new AndroidDriver(new URL("http://127.0.0.1:4747/wd/hub"), capabilities);
        wait = new WebDriverWait(driver, 30);
        System.out.println("launched");
        WebElement idElement = driver.findElement(By.id("mobile-menu-title"));
    } catch (MalformedURLException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
```

We are getting the following error:

log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: An unknown server-side error occurred while processing the command. (Original error: unknown error: com.android.browser is not installed on device 4d00aebfb8b9900f
  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Windows NT 6.1 SP1 x86_64))) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 11.61 seconds
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:58'
System info: host: 'LT0022323', ip: '10.49.146.150', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_40'
Driver info: io.appium.java_client.android.AndroidDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
    at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:109)
    at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:39)
    at com.rjil.cloud.snw.MobileBrowser.main(MobileBrowser.java:40)

**Comment by saikrishna321** [comment]
@NibhaSanghai 

Few things needs to be updated :
1. Please update your node to the latest.
2. Are your running the appium server for Appium GUI. If yes, please start the appium server from command line .(Recommended version 1.4.16.1)
3. I see you have started the server with "automationName":"Selendroid" and the code doesn't do that.

If you're running your tests on GenyMotion you should have the capabilities set to 

```
capabilities.setCapability("browserName", "browser");
```

If your running your tests on real device you should have chrome browser installed and the capabilities set to 

```
capabilities.setCapability("browserName", "browser");
```

https://github.com/saikrishna321/VodQa_MobileAutomationWorkShop/blob/master/VodQA_WorkShop/src/test/java/com/appium/android/test/AndroidWebTest.java#L39
